language: java
script: mvn install -DskipITs
jdk:
- oraclejdk8

branches:
    only:
    - master
    - develop 

notifications:
    email:
    - yollyhideout@gmail.com
    - cvansang94@gmail.com

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

after_success:
    - mvn clean test -DskipITs jacoco:report coveralls:report